spring.application.name=gestion-vacantes
server.port=9090

spring.datasource.url=jdbc:mysql://localhost:3306/gestion_vacantes?useSSL=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=admin123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

jwt.secret=GestionVacantes2026ClaveSecretaSuperSeguraParaHS256JWT
jwt.expiration-ms=28800000

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs


logging.level.org.springframework.security=DEBUG
logging.level.com.gestionvacantes=DEBUG